### PR TITLE
Update to v1.6.7

### PR DESCRIPTION
**Pull request by synapticarbors**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Review by xhochy — CHANGES_REQUESTED** [review]
If CI passes, we should also reset the build number to `0`

**Comment by synapticarbors** [comment]
Looks like this is still failing with the same errors as the other PR. I was hoping the newer compilers would fix this, but evidently not. I'm not sure what the solution is

**Comment by xhochy** [comment]
@synapticarbors The kernel library is too old. Nothing new compilers or a newer libc can fix.

**Pull request closed without merging**
